"""
generate_final_deliverables.py
1. Generates print_plate_all_parts.stl with all parts optimally oriented flat on Z=0.
2. Generates a crystal-clear, step-by-step visual illustration 'how_it_works_explained.png'
   showing exactly how the two 3D-printed parts lock the cable to the housing.
"""

import math
import numpy as np
import trimesh
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import os

target_dir = r"c:\Users\Elliot\Documents\antigravity\hv_lock"
artifact_dir = r"C:\Users\Elliot\.gemini\antigravity\brain\bcff0673-e2b6-492e-8df2-3d38d1a52185"

# Load parts generated by build_c_bracket.py
spine_mesh = trimesh.load(os.path.join(target_dir, "c_bracket_spine.stl"))
keeper_mesh = trimesh.load(os.path.join(target_dir, "c_bracket_keeper.stl"))

# Reference seated parts for visualization
housing_mesh = trimesh.load(os.path.join(target_dir, "testing", "seated_housing.stl"))
connector_mesh = trimesh.load(os.path.join(target_dir, "testing", "seated_connector.stl"))

# ==============================================================================
# 1. OPTIMIZE PRINT ORIENTATION & CREATE COMBINED PRINT PLATE
# ==============================================================================
print("Arranging parts for optimal FDM 3D printing on a single build plate...")

# Part 1: C-Spine
# Optimal orientation: Flat on its top bridge face.
# In native coords, the top bridge is at Z = 28.0 with normal [0, 0, 1].
# We rotate 180 deg around X so the top bridge sits flat on Z = 0 (bed).
spine_print = spine_mesh.copy()
rot_x_180 = trimesh.transformations.rotation_matrix(np.pi, [1, 0, 0])
spine_print.apply_transform(rot_x_180)
# Shift min Z to 0.0
spine_print.apply_translation([0, 0, -spine_print.bounds[0][2]])
# Center in X, position on left side of plate
spine_center_x = (spine_print.bounds[0][0] + spine_print.bounds[1][0]) / 2.0
spine_center_y = (spine_print.bounds[0][1] + spine_print.bounds[1][1]) / 2.0
spine_print.apply_translation([-spine_center_x - 35.0, -spine_center_y, 0])

# Part 2: Slide-In Keeper
# Optimal orientation: Flat on its large rear face (normal [0, 1, 0] in native coords).
# We rotate -90 deg around X so the rear face sits flat on Z = 0.
keeper_print = keeper_mesh.copy()
rot_x_neg90 = trimesh.transformations.rotation_matrix(-np.pi / 2, [1, 0, 0])
keeper_print.apply_transform(rot_x_neg90)
# Shift min Z to 0.0
keeper_print.apply_translation([0, 0, -keeper_print.bounds[0][2]])
# Center in X, position on right side of plate
keeper_center_x = (keeper_print.bounds[0][0] + keeper_print.bounds[1][0]) / 2.0
keeper_center_y = (keeper_print.bounds[0][1] + keeper_print.bounds[1][1]) / 2.0
keeper_print.apply_translation([-keeper_center_x + 35.0, -keeper_center_y, 0])

# Combine into single plate assembly
plate_assembly = trimesh.util.concatenate([spine_print, keeper_print])

print(f"Plate Dimensions (X, Y, Z): {plate_assembly.extents[0]:.1f} x {plate_assembly.extents[1]:.1f} x {plate_assembly.extents[2]:.1f} mm")
print(f"Total Plate Volume: {plate_assembly.volume:.1f} mm³")
print(f"Plate is watertight: {plate_assembly.is_watertight}")

# Export combined plate
out_plate_stl = os.path.join(target_dir, "print_plate_all_parts.stl")
out_plate_obj = os.path.join(target_dir, "print_plate_all_parts.obj")
plate_assembly.export(out_plate_stl)
plate_assembly.export(out_plate_obj)
plate_assembly.export(os.path.join(artifact_dir, "print_plate_all_parts.stl"))
plate_assembly.export(os.path.join(artifact_dir, "print_plate_all_parts.obj"))
print("Saved print_plate_all_parts.stl successfully.")

# ==============================================================================
# 2. GENERATE CRYSTAL CLEAR "HOW IT WORKS" VISUALIZATION
# ==============================================================================
fig = plt.figure(figsize=(26, 17), dpi=180)
plt.subplots_adjust(left=0.03, right=0.97, top=0.93, bottom=0.04, wspace=0.10, hspace=0.16)
fig.patch.set_facecolor('#070d19')

def plot_m(ax, mesh, color, alpha=0.9, edge_color=None):
    m = mesh.copy()
    if len(m.faces) > 3500:
        m = m.simplify_quadric_decimation(3500)
    v = m.vertices
    f = m.faces
    pc = Poly3DCollection(v[f], facecolors=color, alpha=alpha)
    if edge_color:
        pc.set_edgecolor(edge_color)
        pc.set_linewidth(0.2)
    ax.add_collection3d(pc)

def setup_ax(ax, title, elev=24, azim=-45):
    ax.set_xlim(-55, 65)
    ax.set_ylim(-60, 105)
    ax.set_zlim(-30, 50)
    ax.view_init(elev=elev, azim=azim)
    ax.axis('off')
    ax.set_facecolor('#070d19')
    ax.set_title(title, color='white', fontsize=13, weight='bold', pad=12)

# ------------------------------------------------------------------------------
# STEP 1: THE OEM HARDWARE IN YOUR CAR (THE PROBLEM)
# ------------------------------------------------------------------------------
ax1 = fig.add_subplot(2, 2, 1, projection='3d')
plot_m(ax1, housing_mesh, color='#475569', alpha=0.85, edge_color='#64748b')
conn_step1 = connector_mesh.copy()
conn_step1.apply_translation([0, 15.0, 0])
plot_m(ax1, conn_step1, color='#f97316', alpha=0.90, edge_color='#c2410c')
setup_ax(ax1, "STEP 1: The Problem — Unlocked Connector Slips Out")

ax1.text2D(0.02, 0.94, "■ 1. Black Vehicle Outlet Box", transform=ax1.transAxes, color='#94a3b8', weight='bold', fontsize=11)
ax1.text2D(0.02, 0.88, "■ 2. Orange V2L Cable Connector", transform=ax1.transAxes, color='#fb923c', weight='bold', fontsize=11)
ax1.text2D(0.02, 0.80, "• With the original orange slider broken off,", transform=ax1.transAxes, color='#f87171', fontsize=9.5)
ax1.text2D(0.02, 0.74, "  there is nothing locking the plug into the car.", transform=ax1.transAxes, color='#f87171', fontsize=9.5)
ax1.text2D(0.02, 0.68, "• If tugged or vibrated, the plug slips right out!", transform=ax1.transAxes, color='#facc15', weight='bold', fontsize=9.5)

# ------------------------------------------------------------------------------
# STEP 2: PART 1 DROPS OVER THE HOUSING (C-SPINE)
# ------------------------------------------------------------------------------
ax2 = fig.add_subplot(2, 2, 2, projection='3d')
plot_m(ax2, housing_mesh, color='#475569', alpha=0.45, edge_color='#64748b')
plot_m(ax2, connector_mesh, color='#f97316', alpha=0.65, edge_color='#c2410c')
spine_step2 = spine_mesh.copy()
spine_step2.apply_translation([0, 0, 20.0])
plot_m(ax2, spine_step2, color='#0284c7', alpha=0.92, edge_color='#38bdf8')
setup_ax(ax2, "STEP 2: Drop Part 1 (Blue C-Spine) Over the Box")

ax2.text2D(0.02, 0.94, "■ Part 1: Heavy-Duty C-Spine (Cyan)", transform=ax2.transAxes, color='#38bdf8', weight='bold', fontsize=11)
ax2.text2D(0.02, 0.86, "• Upper hook drops over the top lid of the black box.", transform=ax2.transAxes, color='#e2e8f0', fontsize=9.5)
ax2.text2D(0.02, 0.80, "• Left & Right structural legs flank the orange plug.", transform=ax2.transAxes, color='#e2e8f0', fontsize=9.5)
ax2.text2D(0.02, 0.74, "• Anchored directly to the car's rigid module body!", transform=ax2.transAxes, color='#4ade80', weight='bold', fontsize=9.5)

# ------------------------------------------------------------------------------
# STEP 3: PART 2 SLIDES IN TO TRAP THE CABLE (SLIDE-IN KEEPER)
# ------------------------------------------------------------------------------
ax3 = fig.add_subplot(2, 2, 3, projection='3d')
plot_m(ax3, housing_mesh, color='#475569', alpha=0.35, edge_color='#64748b')
plot_m(ax3, connector_mesh, color='#f97316', alpha=0.55, edge_color='#c2410c')
plot_m(ax3, spine_mesh, color='#0284c7', alpha=0.65, edge_color='#38bdf8')
keeper_step3 = keeper_mesh.copy()
keeper_step3.apply_translation([32.0, 0, 0])
plot_m(ax3, keeper_step3, color='#22c55e', alpha=0.95, edge_color='#4ade80')
setup_ax(ax3, "STEP 3: Slide Part 2 (Green Keeper) Into Bottom Track")

ax3.text2D(0.02, 0.94, "■ Part 2: Slide-In Locking Keeper (Green)", transform=ax3.transAxes, color='#4ade80', weight='bold', fontsize=11)
ax3.text2D(0.02, 0.86, "• Slide the keeper in from the right using your thumb.", transform=ax3.transAxes, color='#e2e8f0', fontsize=9.5)
ax3.text2D(0.02, 0.80, "• Its U-cutout passes around the thin rubber cable,", transform=ax3.transAxes, color='#e2e8f0', fontsize=9.5)
ax3.text2D(0.02, 0.74, "  but sits behind the WIDE rigid orange shoulder!", transform=ax3.transAxes, color='#facc15', weight='bold', fontsize=9.5)
ax3.text2D(0.02, 0.68, "• Clicks locked into tactile spring snap detents.", transform=ax3.transAxes, color='#4ade80', fontsize=9.5)

# ------------------------------------------------------------------------------
# STEP 4: MECHANICALLY DEADBOLTED (FORCE LOAD PATH)
# ------------------------------------------------------------------------------
ax4 = fig.add_subplot(2, 2, 4)
ax4.set_facecolor('#0f172a')

# 2D cross section showing the trap
# Box outline
ax4.fill([-48, 0, 0, -48, -48], [-14, -14, 24, 24, -14], color='#334155', alpha=0.9, label='Outlet Box Body')
ax4.fill([-52, -45, -45, -52], [24, 24, 27, 27], color='#475569', label='Box Lid Flange (Top Anchor)')

# Orange Connector Body (Wide section)
ax4.fill([4.7, 59.3, 59.3, 4.7], [-10.4, -9.0, 9.0, 10.4], color='#f97316', alpha=0.85, label='Wide Orange Plug Body (36.1mm)')
# Thin Cable Boot (Narrow section)
ax4.fill([59.3, 85.0, 85.0, 59.3], [-8.5, -8.5, 8.5, 8.5], color='#1e293b', alpha=0.95, label='Narrow Rubber Cable Boot')

# Distinct Orange Shoulder Step
ax4.plot([59.3, 59.3], [9.0, 15.0], color='#ea580c', lw=3.0)
ax4.plot([59.3, 59.3], [-9.0, -15.0], color='#ea580c', lw=3.0)
ax4.text(59.3, -18.0, "RIGID PLUG SHOULDER (Y = 59.3mm)", color='#facc15', weight='bold', fontsize=9.5, ha='center')

# C-Spine Frame (Blue)
ax4.plot([-52, -45, 69.3, 69.3, 59.3, 59.3], [28, 28, 28, -16, -16, -10], color='#38bdf8', lw=3.5, label='Blue C-Spine Frame')
ax4.plot([-52, -52], [28, 19], color='#38bdf8', lw=3.5) # Hook lip

# Slide-In Keeper (Green) - sits right against the shoulder!
ax4.fill([59.3, 65.1, 65.1, 59.3], [-16.0, -16.0, -4.0, -4.0], color='#22c55e', alpha=0.95, label='Green Keeper (Physically Traps Shoulder)')

# Large Arrows showing why pulling fails
ax4.annotate('', xy=(88, 0), xytext=(108, 0), arrowprops=dict(arrowstyle='->', color='#ef4444', lw=3.5))
ax4.text(98, 4, "Pulling on Cable", color='#ef4444', weight='bold', fontsize=10, ha='center')

ax4.annotate('', xy=(59.3, -6), xytext=(52, -6), arrowprops=dict(arrowstyle='->', color='#22c55e', lw=3.5))
ax4.text(45, -4, "Keeper BLOCKS\nShoulder!", color='#4ade80', weight='bold', fontsize=9.5, ha='center')

ax4.annotate('', xy=(-48, 26), xytext=(-35, 33), arrowprops=dict(arrowstyle='->', color='#38bdf8', lw=2.5))
ax4.text(-32, 35, "Spine Anchored\nto Box Lid!", color='#38bdf8', weight='bold', fontsize=9.5)

ax4.set_xlim(-60, 115)
ax4.set_ylim(-26, 45)
ax4.set_aspect('equal')
ax4.set_title("STEP 4: Why It Cannot Pull Out (The Mechanical Trap)", color='white', fontsize=13, weight='bold', pad=10)
ax4.grid(True, color='#1e293b', ls=':', lw=0.8)
ax4.tick_params(colors='#94a3b8', labelsize=9)
ax4.set_xlabel("Y (Length from Housing Wall - mm)", color='#94a3b8', fontsize=10)
ax4.set_ylabel("Z (Elevation - mm)", color='#94a3b8', fontsize=10)
ax4.legend(loc='lower left', fontsize=8.0, facecolor='#070d19', edgecolor='#334155', labelcolor='white')

out_visual = os.path.join(target_dir, "how_it_works_explained.png")
art_visual = os.path.join(artifact_dir, "how_it_works_explained.png")
plt.savefig(out_visual, facecolor=fig.get_facecolor(), edgecolor='none')
plt.savefig(art_visual, facecolor=fig.get_facecolor(), edgecolor='none')
plt.close()
print("Saved how_it_works_explained.png successfully.")
